import Head from 'next/head'
import Image from 'next/image'
import Test from '../src/components/Test'
import Main from '../src/components/Main'

export default function Home() {
  return (
    <div className="">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div style={{ fontFamily: ['Ubuntu', 'sans-serif'], }}>
        <Main />
        <Test />
      </div>
    </div>
  )
}
